from neo4j import GraphDatabase


queries = [
    "MATCH (player:Player {name: 'Aaron Ramsdale'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David Raya'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'James Hillson'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'William Saliba'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ben White'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gabriel'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jurriën Timber'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jakub Kiwior'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Cédric'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Takehiro Tomiyasu'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Oleksandr Zinchenko'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Thomas Partey'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Martin Odegaard'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Leandro Trossard'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jorginho'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fábio Vieira'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mohamed Elneny'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kai Havertz'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Declan Rice'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bukayo Saka'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gabriel Jesus'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Emile Smith Rowe'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gabriel Martinelli'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Eddie Nketiah'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Reiss Nelson'}) MATCH (team:Team {name: 'Arsenal'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Horatiu Moldovan'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jan Oblak'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'José María Giménez'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'César Azpilicueta'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gabriel'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Stefan Savić'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nahuel Molina'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mario Hermoso'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Reinildo'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rodrigo De Paul'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Koke'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Saúl Ñíguez'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Thomas Lemar'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Samuel Lino'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marcos Llorente'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rodrigo Riquelme'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sergio Guerrero'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Arthur Vermeeren'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Axel Witsel'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Antoine Griezmann'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Memphis Depay'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ángel Correa'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Álvaro Morata'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Álex Calatrava'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Abdellah Raihani'}) MATCH (team:Team {name: 'Atletico Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marc-André ter Stegen'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Iñaki Peña'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'João Cancelo'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alejandro Balde'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ronald Araújo'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Iñigo Martínez'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Andreas Christensen'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marcos Alonso'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jules Koundé'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Pablo Martín Páez Gavira'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Pedro González López'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Oriol Romeu'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sergi Roberto'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Frenkie de Jong'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'İlkay Gündoğan'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Unai Hernandez'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ferran Torres'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Robert Lewandowski'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Raphinha'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'João Félix'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Vitor Roque'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Pau Victor'}) MATCH (team:Team {name: 'Barcelona'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Manuel Neuer'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Daniel Peretz'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sven Ulreich'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dayot Upamecano'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Minjae Kim'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matthijs de Ligt'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Eric Dier'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bouna Sarr'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Raphaël Guerreiro'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sacha Boey'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tarek Buchmann'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Noussair Mazraoui'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joshua Kimmich'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Leon Goretzka'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Leroy Sané'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Eric Maxim Choupo-Moting'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alphonso Davies'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Konrad Laimer'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jamal Musiala'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Serge Gnabry'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Harry Kane'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kingsley Coman'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bryan Zaragoza'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Thomas Müller'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mathys Tel'}) MATCH (team:Team {name: 'Bayern Munich'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gregor Kobel'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Silas Ostrzinski'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alexander Meyer'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marcel Lotka'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nico Schlotterbeck'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ramy Bensebaini'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mats Hummels'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ian Maatsen'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Emre Can'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Niklas Süle'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Julian Ryerson'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Salih Özcan'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Felix Nmecha'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jadon Sancho'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marco Reus'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Julien Duranville'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marius Wolf'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Julian Brandt'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marcel Sabitzer'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jamie Bynoe-Gittens'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sébastien Haller'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Niclas Füllkrug'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Youssoufa Moukoko'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Donyell Malen'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Karim Adeyemi'}) MATCH (team:Team {name: 'Dortmund'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Stefan Ortega'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ederson'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Scott Carson'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kyle Walker'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rúben Dias'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'John Stones'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nathan Aké'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sergio Gómez'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joško Gvardiol'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Manuel Akanji'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mateo Kovačić'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jack Grealish'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rodri'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kevin De Bruyne'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bernardo Silva'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matheus Nunes'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Phil Foden'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Erling Haaland'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jérémy Doku'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Julián Álvarez'}) MATCH (team:Team {name: 'Manchester City'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Thibaut Courtois'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Andriy Lunin'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kepa Arrizabalaga'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fran González'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dani Carvajal'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Éder Militão'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David Alaba'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nacho Fernández Iglesias'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fran García'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Antonio Rüdiger'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Antonio Rüdiger'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Vinicius Tobias'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jude Bellingham'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Toni Kroos'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Luka Modrić'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Eduardo Camavinga'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Federico Valverde'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lucas Vázquez'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Aurélien Tchouameni'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dani Ceballos'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Brahim Díaz'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Arda Güler'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Vinícius Júnior'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rodrygo'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joselu'}) MATCH (team:Team {name: 'Real Madrid'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Keylor Navas'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alexandre Letellier'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Arnau Tenas'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gianluigi Donnarumma'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Achraf Hakimi'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Presnel Kimpembe'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marquinhos'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lucas Hernández'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nordi Mukiele'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lucas Beraldo'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Milan Škriniar'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Manuel Ugarte'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fabián Ruiz'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Danilo'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Vitinha'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kang-in Lee'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Carlos Soler'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Warren Zaïre-Emery'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kylian Mbappé'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gonçalo Ramos'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ousmane Dembélé'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marco Asensio'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Randal Kolo Muani'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bradley Barcola'}) MATCH (team:Team {name: 'PSG'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kamil Grabara'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kevin Diks'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Denis Vavro'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Christian Sørensen'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nicolai Boilesen'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Peter Ankersen'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Birger Meling'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Scott McKenna'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Viktor Claesson'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Magnus Mattsson'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mohamed Elyounoussi'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lukas Lerager'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Diogo Gonçalves'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jordan Larsson'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Andreas Cornelius'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Elias Achouri'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rasmus Falk'}) MATCH (team:Team {name: 'Copenhagen'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Diogo Costa'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fábio Cardoso'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Eduardo Gabriel Aquino Cossa'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Zaidu'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jorge Sánchez'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Wendell'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Otávio'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Stephen Eustáquio'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marko Grujić'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nico González'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Iván Jaime'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'André Franco'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alan Varela'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Romário Baró'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mehdi Taremi'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Pepe'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Galeno'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Danny Namaso'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: ' João Mário'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Toni Martínez'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Evanilson'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gonçalo Borges'}) MATCH (team:Team {name: 'Porto'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yann Sommer'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Emil Audero'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Denzel Dumfries'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Stefan de Vrij'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Francesco Acerbi'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Benjamin Pavard'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Carlos Augusto'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yann Bisseck'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Federico Dimarco'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matteo Darmian'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alessandro Bastoni'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Davy Klaassen'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Davide Frattesi'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Hakan Çalhanoğlu'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kristjan Asllani'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Henrikh Mkhitaryan'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nicolò Barella'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marko Arnautović'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marcus Thuram'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lautaro Martínez'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alexis Sánchez'}) MATCH (team:Team {name: 'Inter'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ivan Provedel'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Luca Pellegrini'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Patric'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alessio Romagnoli'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nicolò Casale'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Elseid Hysaj'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Manuel Lazzari'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mario Gila'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matías Vecino'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Daichi Kamada'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Felipe Anderson'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matteo Guendouzi'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Luis Alberto'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Danilo Cataldi'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nicolò Rovella'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Adam Marušić'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Pedro Rodríguez'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ciro Immobile'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gustav Isaksen'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Taty Castellanos'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mattia Zaccagni'}) MATCH (team:Team {name: 'Lazio'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Péter Gulácsi'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Janis Blaswich'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mohamed Simakan'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Christopher Lenz'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Willi Orbán'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lukas Klostermann'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David Raum'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Castello Lukeba'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Benjamin Henrichs'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Eljif Elmas'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Amadou Haidara'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nicolas Seiwald'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Christoph Baumgartner'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Xaver Schlager'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kevin Kampl'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dani Olmo'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yussuf Poulsen'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Loïs Openda'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Xavi Simons'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Benjamin Šeško'}) MATCH (team:Team {name: 'Leipzig'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alex Meret'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Natan'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Juan Jesus'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mário Rui'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Amir Rrahmani'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mathías Olivera'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Giovanni Di Lorenzo'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Leo Østigård'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Hamed Traorè'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jens Cajuste'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jesper Lindstrøm'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Stanislav Lobotka'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'André-Frank Zambo Anguiss'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Victor Osimhen'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Giovanni Simeone'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matteo Politano'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Cyril Ngonge'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Khvicha Kvaratskhelia'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Giacomo Raspadori'}) MATCH (team:Team {name: 'Napoli'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Walter Benítez'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Shurandy Sambo'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jordan Teze'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Armando Obispo'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'André Ramalho'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Armel Bella-Kotchap'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sergiño Dest'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mauro Júnior'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Olivier Boscagli'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'CJ Egan-Riley'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Patrick Van Aanholt'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Malik Tillman'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Guus Til'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jerdy Schouten'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joey Veerman'}) MATCH (team:Team {name: 'PSV'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alejandro Remiro'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Álvaro Odriozola'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Aritz Elustondo'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kieran Tierney'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Hamari Traoré'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jon Pacheco'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Robin Le Normand'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Javier Galán'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jon Aramburu'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Martin Zubimendi'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Igor Zubeldia'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mikel Merino'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mikel Oyarzabal'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Arsen Zakharyan'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jon Ander Olasagasti'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jon Magunacelaya'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ander Barrenetxea'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Carlos Fernández'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sheraldo Becker'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Takefusa Kubo'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Umar Sadiq'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'André Silva'}) MATCH (team:Team {name: 'Real Sociedad'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jean Butez'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Senne Lammens'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ritchie De Laet'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Björn Engels'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Owen Wijndal'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Toby Alderweireld'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mandela Keita'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jelle Bataille'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Soumaula Coulibaly'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gyrano Kerk'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alhassan Yusuf'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jacob Ondrejka'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Chidera Ejuke'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jurgen Ekkelenkamp'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Arthur Vermeeren'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'George Ilenikhena'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Michel-Ange Balikwisha'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Arbnor Muja'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Vincent Janssen'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Anthony Valencia'}) MATCH (team:Team {name: 'Antwerp'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Anatoliy Trubin'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Morato'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alexander Bah'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David Jurásek'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Juan Bernat'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nicolás Otamendi'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fredrik Aursnes'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Orkun Kökçü'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'João Mário2'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Chiquinho'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Florentino'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David Neres'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Arthur Cabral'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ángel Di María'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gonçalo Guedes'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Casper Tengstedt'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rafa Silva'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Petar Musa'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tiago Gouveia'}) MATCH (team:Team {name: 'Benfica'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matheus'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Victor Gómez'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sikou Niakaté'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Serdar Saatçı'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'José Fonte'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Paulo Oliveira'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Josafat Mendes'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Adrián Marín'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Cristian Borja'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Al Musrati'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'André Horta'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rodrigo Zalazar'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Vitor Carvalho'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Pizzi'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'João Moutinho'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'André Castro'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bruma'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Abel Ruiz'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Álvaro Djaló'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rony Lopes'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ricardo Horta'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Simon Banza'}) MATCH (team:Team {name: 'Braga'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joe Hart'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alistair Johnston'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Greg Taylor'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gustaf Lagerbielke'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Liam Scales'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nathaniel Phillips'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Cameron Carter-Vickers'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Reo Hatate'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Stephen Welsh'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Luis Palma'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kyogo Furuhashi'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Hyunjun'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Odin Thiago Holm'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tomoki Iwata'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Paulo Bernardo'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matthew O Riley'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Callum McGregor'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'James Forrest'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David Turnbull'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Hyeongyu Oh'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Daizen Maeda'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mikey Johnston'}) MATCH (team:Team {name: 'Celtic'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Omri Glazer'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Miloš Degenek'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Uroš Spajić'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Aleksandar Dragović'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Milan Rodić'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nasser Djiga'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mirko Ivanić'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marko Stamenic'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Guélor Kanga'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Aleksandar Katai'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kings Kangwa'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Osman Bukari'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Srdjan Mijailović'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Vladimir Lučić'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Inbeom Hwang'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Uroš Kabić'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Stefan Mitrović'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Cherif Ndiaye'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Peter Olayinka'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jean-Philippe Krasso'}) MATCH (team:Team {name: 'Red Star FC'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Justin Bijlow'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Timon Wellenreuther'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bart Nieuwkoop'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Thomas Beelen'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lutsharel Geertruida'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Quilindschy Hartman'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marcos Lopez'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Gernot Trauner'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dávid Hancko'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ramiz Zerrouki'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Quinten Timber'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Calvin Stengs'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Thomas Van Den Belt'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mats Wieffer'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ondřej Lingr'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alireza Jahanbakhsh'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ayase Ueda'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Javairo Dilrosun'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Igor Paixão'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Luka Ivanušec'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yankuba Minteh'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Leo Sauer'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Santiago Giménez'}) MATCH (team:Team {name: 'Feyenoord'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fernando Muslera'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Angeliño'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Davinson Sánchez'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kaan Ayhan'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Victor Nelsson'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Abdülkerim Bardakci'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kazimcan Karataş'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sacha Boey'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kerem Demirbay'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Hakim Ziyech'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sérgio Oliveira'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lucas Torreira'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tanguy Ndombélé'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kerem Aktürkoğlu'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mauro Icardi'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dries Mertens'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Wilfried Zaha'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tetê'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bariş Alper Yilmaz'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Cédric Bakambu'}) MATCH (team:Team {name: 'Galatasaray'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Brice Samba'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ruben Aguilar'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Deiver Machado'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kevin Danso'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Facundo Medina'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Massadio Haïdara'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jonathan Gradit'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Abdukodir Khusanov'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Przemysław Frankowski'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Salis Abdul Samed'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David Pereira Da Costa'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Andy Diouf'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Neil El Aynaoui'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nampalys Mendy'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Adrien Thomasson'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Florian Sotoca'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Elye Wahi'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Angelo Fulgini'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Wesley Saïd'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Morgan Guilavogui'}) MATCH (team:Team {name: 'Lens'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'André Onana'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Victor Lindelöf'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Harry Maguire'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lisandro Martínez'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sergio Reguilón'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Raphaël Varane'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Diogo Dalot'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Luke Shaw'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Aaron Wan-Bissaka'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jonny Evans'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sofyan Amrabat'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mason Mount'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bruno Fernandes'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Christian Eriksen'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Casemiro'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Facundo Pellistri'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Scott McTominay'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Anthony Martial'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marcus Rashford'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rasmus Højlund'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alejandro Garnacho'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Antony'}) MATCH (team:Team {name: 'Manchester United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mike Maignan'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marco Sportiello'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Davide Calabria'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Theo Hernández'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Pierre Kalulu'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fikayo Tomori'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Simon Kjær'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Malick Thiaw'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alessandro Florenzi'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yacine Adli'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ruben Loftus-Cheek'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tijjani Reijnders'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tommaso Pobega'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rade Krunić'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yunus Musah'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Olivier Giroud'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rafael Leão'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Christian Pulišić'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Luka Jović'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Noah Okafor'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Samuel Chukwueze'}) MATCH (team:Team {name: 'Milan'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Martin Dúbravka'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nick Pope'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kieran Trippier'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sven Botman'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fabian Schär'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jamaal Lascelles'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Matt Targett'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tino Livramento'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dan Burn'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sandro Tonali'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Harvey Barnes'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lewis Hall'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Miguel Almirón'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sean Longstaff'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Bruno Guimarães'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joelinton'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Callum Wilson'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Anthony Gordon'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alexander Isak'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jacob Murphy'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joe Willock'}) MATCH (team:Team {name: 'Newcastle United'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nico Mantl'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alexander Schlager'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Aleksa Terzić'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kamil Piątkowski'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Samson Baidoo'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Andreas Ulmer'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Oumar Solet'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Strahinja Pavlović'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Leandro Morgalla'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Amar Dedić'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nicolás Capaldo'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dijon Kameri'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Luka Sučić'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Maurits Kjærgaard'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mads Bidstrup'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lucas Gourna-Douath'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Oscar Gloukh'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Amankwah Forson'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fernando'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Karim Konaté'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sékou Koita'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Petar Ratkov'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Roko Šimić'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dorgeles Nene'}) MATCH (team:Team {name: 'Salzburg'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Federico Gattoni'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marko Dmitrović'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ørjan Nyland'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Adriá Pedrosa'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sergio Ramos'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Tanguy Nianzou'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marcos Acuña'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Loïc Badé'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Nemanja Gudelj'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joan Jordán'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ivan Rakitić'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Djibril Sow'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fernando2'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Óliver Torres'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Boubakary Soumaré'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lucas Ocampos'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Suso'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rafa Mir'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dodi Lukébakio'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mariano Díaz'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Youssef En-Nesyri'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jesús Navas'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Erik Lamela'}) MATCH (team:Team {name: 'Sevilla'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dmytro Riznyk'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Stav Lemkin'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Valeriy Bondar'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Giorgi Gocholeishvili'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Irakli Azarov'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mykola Matviyenko'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yukhym Konoplia'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yaroslav Rakitskyy'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Taras Stepanenko'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Eguinaldo'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Dmytro Kryskiv'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Marian Shved'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Georgiy Sudakov'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Oleksandr Zubkov'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Artem Bondarenko'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Novatus Miroshi'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Yehor Nazaryna'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Newerton'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Olexiy Kashchuk'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Danylo Sikan'}) MATCH (team:Team {name: 'Shakhtar Donetsk'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Frederik Rønnow'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Paul Jaeckel'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Diogo Leite'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Danilho Doekhi'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Robin Gosens'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Josip Juranović'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Leonardo Bonucci'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jérôme Roussillon'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Christopher Trimmel'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Robin Knoche'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Brenden Aaronson'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Rani Khedira'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Janik Haberer'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Aïssa Laïdouni'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lucas Tousart'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Alex Král'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Aljoscha Kemlein'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kevin Volland'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David Fofana'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kevin Behrens'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sheraldo Becker'}) MATCH (team:Team {name: 'Union Berlin'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Anthony Racioppi'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'David von Ballmoos'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Mohamed Ali Camara'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Saidy Janko'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Noah Persson'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ulisses Garcia'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Loris Benito'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Lewin Blum'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Fabian Lustenberger'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Filip Ugrinic'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Łukasz Łakomy'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Kastriot Imeri'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Miguel Chaiwa'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Cheikh Niasse'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Donat Rrudhani'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Sandro Lauper'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Darian Males'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Cédric Itten'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Ebrima Colley'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Meschack Elia'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Jean-Pierre Nsame'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Silvère Ganvoula'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)",
    "MATCH (player:Player {name: 'Joel Monteiro'}) MATCH (team:Team {name: 'Young Boys'}) MERGE (player)-[:PLAYS_FOR]->(team)"
]


def insert_affiliation():
    count = 0
    # Function to execute queries

    def execute_queries(driver):
        count = 0
        with driver.session() as session:
            for query in queries:
                session.run(query)
                count += 1
            return count

    import os

    NEO4J_URI = os.getenv("NEO4J_URI")
    NEO4J_USERNAME = os.getenv("NEO4J_USERNAME")
    NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")
    # Connect to Neo4j
    driver = GraphDatabase.driver(
        NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD))

    # Execute queries
    count = execute_queries(driver)

    # Close the connection
    driver.close()

    print(count)  # 356

    # with GraphDatabase.driver(uri,  auth=(username, password)) as driver:
    #    driver.verify_connectivity()
